### ISSUE TITLE
appel du squelette album

### ISSUE THREAD

**Issue by ubiquando** [geodiversite/geodiversite_balades#1]
Je ne trouve pas où est utilisé/appelé le squelette album (du plugin geodiversite_albums).
C'est le seul squelette que j'aie trouvé qui permette de créer une balade (geodiversite_albums/extra/album.html)
Y en a-t-il un autre ?
Le souci, c'est qu'il y a plusieurs endroits où on appelle #URL_COLLECTION, ce qui amène vers le squelette collection, et non album.
De plus, le .htaccess recommandé redirige, me semble-t-il, ?page=albumxx vers ?page=collection&id_collection=xx

J'ai encore sûrement raté qqchose, mais quoi/où ?

**Comment by ubiquando** [comment]
finalement, j'ai recopié le contenu de extra/album.html vers un nouveau fichier extra/collection.html, et ça permet d'utiliser la fonctionnalité des balades.
Mais ça n'utilise toujours pas le squelette album.html

**Comment by brunob** [comment]
Tu as bien activé les urls geodiv dans la configuration des urls de SPIP ?

**Comment by ubiquando** [comment]
ma foi non, je n'avais pas vu cela du tout... Je vais l'ajouter à la doc !
Et en effet, c'est mieux !!!
je vais enlever mon extra/collection.html et regarderai cela.
MERCI !

**Comment by brunob** [comment]
Super, tu peux l'ajouter dans la partie qui mentionne les urls persos et leur htaccess.
