### ISSUE TITLE
ajout kml à une balade impossible

### ISSUE THREAD

**Issue by ubiquando** [geodiversite/geodiversite_balades#3]
une collection "balade".
page editer_balade => soit on ajoute des points sur une trace, soit on peut importer un fichier kml.
Lorsque j'ajoute un kml, on peut sélectionner un fichier, puis "entregistrer", rien ne se passe, apparemment pas d'upload, rien de nouveau dans la table spip_documents

**Comment by brunob** [comment]
Vu, je confirme, je m'y colle.

**Comment by brunob** [comment]
Corrigé, merci pour le signalement :)
